### ISSUE TITLE
Problemas na leitura do site da Prefeitura de Marmeleiro

### ISSUE THREAD

**Issue by iservport** [CodeForCuritiba/c4c-gestao-br#5]
Na versão atual do crawler, já podemos extrair uma página html após enviarmos um formulário preenchido. Este passo, feito automaticamente pelo nosso programa, seria o equivalente a uma pessoa navegar até o portal da Prefeitura de Marmeleiro, seguir o botão "Portal da Transparência", escolher "Administração" >> "Licitações" no menu horizontal e preencher o formulário manualmente. 

**O problema**: o carregamento completo da página é interrompido pelo alerta de "Aguarde", como na figura abaixo:

![captura de tela 2017-03-22 as 11 58 51](https://cloud.githubusercontent.com/assets/992887/24204381/0cbefd3e-0ef7-11e7-8a00-c629e3ba49a6.png)

O html que recebemos é interrompido. Abaixo um exemplo extraído do logo do programa:

![captura de tela 2017-03-22 as 12 04 07](https://cloud.githubusercontent.com/assets/992887/24204681/ff89567c-0ef7-11e7-91fe-54cb15ebdfc5.png)

Precisamos, de alguma maneira, evitar a conclusão da página enquanto o alerta não se fecha.

**Comment by nerijunior** [comment]
@iservport o carregamento acaba porque as chamadas começam a serem feitas por AJAX, alguma ideia de como colocar uma alternativa para isso? O básico seria interceptar as chamadas ajax ( complicado ) ou fazer manualmente as próximas varreduras, fazemos uma lista de urls com os argumentos dinâmicos e conforme a leitura desta página criamos os próximos links a serem seguidos.

**Comment by iservport** [comment]
Pensei nisto, mas veja:

![captura de tela 2017-03-22 as 13 47 11](https://cloud.githubusercontent.com/assets/992887/24209929/475cdac4-0f06-11e7-9fc4-584fc87f8710.png)

As chamadas ajax que se seguem são só 2 e elas retornam outra coisa. Copio aqui as requisições:

    Request URL:http://portal.marmeleiro.pr.gov.br/pronimtb/acao.asp_=1490201167937&acao=BuscaFavoritos
    Request Method:GET
    Status Code:200 OK

    Request URL:http://portal.marmeleiro.pr.gov.br/pronimtb/acao.asp?acao=RetornaProdutosTB
    Request Method:GET
    Status Code:200 OK

Acredito que seja um problema de timeout.

**Comment by iservport** [comment]
Agora temos um novo projeto capaz de ler o site. Ele é em Python e simula um browser para acessar cada site.
